### ISSUE TITLE
Add a test program

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL_gesture#1]
testgesture.c from SDL2 needs a little cleanup, and the SDLtest dependency removed, but it should in here as an example program.

(or _something_, it doesn't have to be testgesture)

**Comment by madebr** [comment]
Is the plan to support SDL2 on the main branch?
And later on, rename main to SDL2 and do SDL3 work on main?

**Comment by icculus** [comment]
#3 added the test program, but we need to clean out libSDLtest still.

**Comment by icculus** [comment]
@1bsyl came through on this! Closing!
