### ISSUE TITLE
testgesture does not show window

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_gesture#6]
`testgesture_sdl2` does not show a window with wayland video driver.
`testgesture_sdl3` does not show a window with both x11 and wayland video driver.

**Comment by 1bsyl** [comment]
@madebr 
it sounds strange. with the latest version ? can you print some error with `SDL_Log("error = %s", SDL_GetError());`

**Comment by madebr** [comment]
```
INFO: error = No hardware accelerated renderers available
```

**Comment by madebr** [comment]
But that error is also printed when running `testgesture_sdl2` with x11, where a window is shown.

**Comment by 1bsyl** [comment]
does it exit after calling SDL_CreateWindowAndRenderer() ? 
can you 
SDL_Log("%p %p", g_window,  g_renderer);

**Comment by 1bsyl** [comment]
could you build with a plain gcc/clang command  ? 
+ make sure it loads the corrects lib ? 
"ldd testgesture_sdl3"

**Comment by 1bsyl** [comment]
also add:
SDL_LogSetAllPriority(SDL_LOG_PRIORITY_VERBOSE);

**Comment by 1bsyl** [comment]
I also have the "hardware accelerated renderers available" 
but the window gray is displayed

**Comment by 1bsyl** [comment]
```
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
DEBUG: Renderer already associated with window
DEBUG: Renderer already associated with window
DEBUG: No hardware accelerated renderers available
```

**Comment by 1bsyl** [comment]
can you double check ? updated with: 
https://github.com/libsdl-org/SDL_gesture/commit/8017c5dc3ebb94413fd57d0d212d1d996832a7c4

**Comment by madebr** [comment]
I forgot the hint `SDL_VIDEODRIVER` was renamed to `SDL_VIDEO_DRIVER` for SDL3.
Doing that, SDL2 and SDL3 have the same behavior: no window is shown for SDL3 with wayland video driver, a grey one for SDL2

I created an archive with all the logs, created by the following script:
```sh
#!/usr/bin/env sh

git diff >verbose-logging.patch

SDL_VIDEO_DRIVER=wayland test/testgesture_sdl3 2>sdl3_wayland.txt
SDL_VIDEO_DRIVER=x11 test/testgesture_sdl3 2>sdl3_x11.txt
SDL_VIDEODRIVER=wayland test/testgesture_sdl2 2>sdl2_wayland.txt
SDL_VIDEODRIVER=x11 test/testgesture_sdl2 2>sdl2_x11.txt

ldd test/testgesture_sdl2 >ldd_testgesture_sdl2.txt
ldd test/testgesture_sdl3 >ldd_testgesture_sdl3.txt

tar -c -z -f testgesture-logs.tar.gz s.sh verbose-logging.patch sdl2_wayland.txt sdl2_x11.txt sdl3_wayland.txt sdl3_x11.txt ldd_testgesture_sdl2.txt ldd_testgesture_sdl3.txt
```
[testgesture-logs.tar.gz](https://github.com/libsdl-org/SDL_gesture/files/10252685/testgesture-logs.tar.gz)

**Comment by madebr** [comment]
> can you double check ? updated with: [8017c5d](https://github.com/libsdl-org/SDL_gesture/commit/8017c5dc3ebb94413fd57d0d212d1d996832a7c4)

Yup, that makes a window appear for wayland as well.
[testgesture-logs.tar.gz](https://github.com/libsdl-org/SDL_gesture/files/10252690/testgesture-logs.tar.gz)

**Comment by 1bsyl** [comment]
so it's all ok for testgesture now ?

**Comment by madebr** [comment]
Yes, I'll close it.
Thanks for helping me troubleshoot.

**Comment by 1bsyl** [comment]
but that's strange, let double check something ... 2 min

**Comment by 1bsyl** [comment]
does this open a window ?

```
static SDL_Window *g_window = NULL;
static SDL_Renderer *g_renderer = NULL;
static void
loop(void)
{
   SDL_Event event;
    while (SDL_PollEvent(&event)) {
        switch (event.type) {
        case SDL_QUIT:
           exit(1);
           break;
        case SDL_KEYDOWN:
            switch (event.key.keysym.sym) {
            case SDLK_ESCAPE:
               exit(1);
               break;
            }
            break;
        }
    }
}

int main(int argc, char *argv[]) {
    if (SDL_CreateWindowAndRenderer(640, 480, 0, &g_window, &g_renderer) < 0) {
       return -1;
    }
    while (1) {
        loop();
        SDL_Delay(20);
    }
    SDL_DestroyRenderer(g_renderer);
    SDL_DestroyWindow(g_window);
    return 0;
}
```

**Comment by 1bsyl** [comment]
and if you add 
`SDL_Surface *screen = SDL_GetWindowSurface(g_window);`
before `loop();`
?

**Comment by madebr** [comment]
The program has the same behavior: screen for x11, no screen for wayland.

I think you're onto something:
`SDL_Log("screen=%p", screen);` prints `INFO: screen=(nil)` for wayland and a pointer for x11.

**Comment by 1bsyl** [comment]
@madebr 
so the issue is when adding " SDL_Surface *screen = SDL_GetWindowSurface(g_window); " ?

**Comment by madebr** [comment]
No, the window for wayland does not appear in both cases, so the main issue remains.
I was just saying `SDL_GetWindowSurface` returns a null pointer for wayland, and a non-null one for x11.

**Comment by madebr** [comment]
I've created similar logs for your new test case.

[testgesture-logs.tar.gz](https://github.com/libsdl-org/SDL_gesture/files/10252732/testgesture-logs.tar.gz)

**Comment by 1bsyl** [comment]
and simply ? (just changing the main). no need for the logs.
could this be the title missing ?

```
int main(int argc, char *argv[]) {
    g_window = SDL_CreateWindow(NULL, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, 0);
    if (g_window == NULL) {
       SDL_Log("no window");
       return -1;
    }
    while (1) {
        loop();
        SDL_Delay(20);
    }
    SDL_DestroyRenderer(g_renderer);
    SDL_DestroyWindow(g_window);
    return 0;
}
```

**Comment by madebr** [comment]
The beaviour remains: no window is shown with no output to stdout.
The loop is being executed, but no window.
So I have to exit the program with CTRL+C.

**Comment by 1bsyl** [comment]
ok, in fact, it needs a mandatory call to SDL_UpdateWindowSurface(g_window) ...so maybe not a bug

**Comment by 1bsyl** [comment]
will create an issue on SDL anyway ..

**Comment by 1bsyl** [comment]
thanks for the help!

**Comment by 1bsyl** [comment]
https://github.com/libsdl-org/SDL/issues/6834
